### ISSUE TITLE
[Feature Request] - An option for data sharing without encryption

### ISSUE THREAD

**Issue by ritsource** [datash/datash#3]
## An option for data sharing without Encryption
Add a button named something like "Quick Send", beside "Send Securely" button.
On that option user can send data without for **encryption**, hence without waiting for **encryption**.

**Comment by rousan** [comment]
Thank you for the feedback @ritsource, I will add this feature as soon as possible.

**Comment by rousan** [comment]
This feature is released: https://datash.co/
